services:
  - type: web
    name: surakshagrid-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: singapore
    healthCheckPath: /health
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_NAME
        value: SurakshaGrid
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: surakshagrid-postgis
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: '["*"]'

databases:
  - name: surakshagrid-postgis
    databaseName: surakshagrid
    user: surakshagrid
    plan: starter
    region: singapore
